const mongoose = require("mongoose");

var HreSchema= new mongoose.Schema({
     ID  : String,
     ProfileName  : String ,
     NameEnglish:String,
     CodeEmp  :  String ,
     CodeTax  :  String ,
     CodeAttendance  :  String ,
     StatusSyn  :  String ,
     DateHire  :  Date ,
     DateEndProbation  :  Date,
     DateQuit  :  Date ,
     WorkGroupID  : String,
     OrgStructureID  :  String ,
     PositionID  :  String ,
     DateOfEffect  :  Date ,
     CostCentreID  : String,
     LaborType  :  String ,
     WorkingPlace  : String,
     Supervisor  : String,
     Gender  :  String,
     DateOfBirth  :  Date ,
     PlaceOfBirth  : String ,
     NationalityID:String,
     EthnicID:String,
     ReligionID:String,
     IDNo:String,
     IDDateOfIssue:Date,
     IDPlaceOfIssue:String,
     PassportNo:String,
     PassportDateOfExpiry:Date,
     PassportDateOfIssue:Date,
     PassportPlaceOfIssue:String,
     Cellphone  :  String ,
     JobTitleID  :  String,
     PayrollGroupID  : String,
     EducationLevelID  : String ,
     ResReasonID:String,
     DateCreate:Date,
     DateUpdate:Date,
     PasswordPaySlip  :  String ,
     DateApplyAttendanceCode:Date,
     ShopID:String,
     PAddress:String,
     ContractTypeID:String,
     CompanyID  :  String,
     SortID:Number
});
module.exports = mongoose.model( "Hre_Profile" , HreSchema);